### ISSUE TITLE
python 3.11 build

### ISSUE THREAD

**Issue by micahj** [gfmio/asyncio-gevent#7]
Hi folks, 
Nice project.
Just tried building with py 3.11.0 and I think its giving a similar err to gevents build a few weeks back, It failed with error: unknown type name ‘CFrame’.

Cheers

**Comment by gfmio** [comment]
Thanks, I'll look into this

**Comment by gfmio** [comment]
I've just released version 0.2.2 which passes all tests on 3.11. Can you please check if this also works for you?
